version: '0.2'
author: Jan Kristinus
supportpage: www.redaxo.org/de/forum/

requires:
  addons:
    structure:
      min-version: '1.3'
      plugins:
        content:
          min-version: '1.3'