version: '1.3'
author: 'Markus Staab'
supportpage: www.redaxo.org/de/forum/

name: 'translate:modules'
perm: isAdmin
navigation:
  block: system
  prio: 40
pages:
  - ['', 'translate:modules']
  - ['actions', 'translate:actions']