name: 'Templates'
version: '1.3'
author: Markus Staab
supportpage: www.redaxo.org/de/forum/
perm: admin[]
navigation:
  block: system
  prio: 30
  
requires:
  addons:
    modules:
      min-version: '1.3'