version: '1.3'
name: Meta Infos
perm: admin[]
author: 'Markus Staab, Jan Kristinus'
supportpage: www.redaxo.org/de/forum/

pages:
  - ['', 'translate:article']
  - ['categories', 'translate:categories']
  - ['media', 'translate:media']

requires:
  addons:
    structure:
      min-version: '1.3'
    mediapool:
      min-version: '1.3'